export default [
  {
    id: 1,
    name: "",
    tagline: "",
    image: require("../../assets/images/couverture-face-tome1-debutants.png"),
  },
  {
    id: 2,
    name: "",
    tagline: "",
    image: require("../../assets/images/page1.png"),
  },
  {
    id: 3,
    name: "",
    tagline: "",
    taglineCTA: "",
    image: require("../../assets/images/page2.png"),
  },
  {
    id: 4,
    name: "",
    tagline: "",
    taglineCTA: "",
    image: require("../../assets/images/page3.png"),
  },
  {
    id: 5,
    name: "",
    tagline: "",
    taglineCTA: "",
    image: require("../../assets/images/page4.png"),
  },
  {
    id: 6,
    name: "",
    tagline: "",
    taglineCTA: "",
    image: require("../../assets/images/page5.png"),
  },
  {
    id: 8,
    name: "",
    tagline: "",
    taglineCTA: "",
    image: require("../../assets/images/page7.png"),
  },
  {
    id: 9,
    name: "",
    tagline: "",
    taglineCTA: "",
    image: require("../../assets/images/page8.png"),
  },
  {
    id: 10,
    name: "",
    tagline: "",
    taglineCTA: "",
    image: require("../../assets/images/page9.png"),
  },
  {
    id: 11,
    name: "",
    tagline: "",
    taglineCTA: "",
    image: require("../../assets/images/page10.png"),
  },
  {
    id: 12,
    name: "",
    tagline: "",
    taglineCTA: "",
    image: require("../../assets/images/page11.png"),
  },
  {
    id: 13,
    name: "",
    tagline: "",
    taglineCTA: "",
    image: require("../../assets/images/page12.png"),
  },
  {
    id: 14,
    name: "",
    tagline: "",
    taglineCTA: "",
    image: require("../../assets/images/page13.png"),
  },
];
